name: Grab M3U8 URLs

on:
  schedule:
    - cron: '0 * * * *' # This runs the action hourly
  workflow_dispatch: # Manually trigger the workflow

jobs:
  grab-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Grab M3U8 URLs
        run: |
          URLS=("https://s2watch.link/player.php?id=chftknovasportprime" "https://s2watch.link/player.php?id=chftknovasport1" "https://s2watch.link/player.php?id=chftknovasport2" "https://s2watch.link/player.php?id=chftknovasport3" "https://s2watch.link/player.php?id=chftknovasport4" "https://s2watch.link/player.php?id=chftknovasport5" "https://s2watch.link/player.php?id=chftkcosmote1" "https://s2watch.link/player.php?id=chftkcosmote2" "https://s2watch.link/player.php?id=chftkcosmote3" "https://s2watch.link/player.php?id=chftkcosmote4" "https://s2watch.link/player.php?id=chftkcosmote5" "https://s2watch.link/player.php?id=chftkcosmote6" "https://s2watch.link/player.php?id=chftkcosmote7" "https://s2watch.link/player.php?id=chftkcosmote8" "https://s2watch.link/player.php?id=chftkcosmote9")
          for URL in "${URLS[@]}"; do
            M3U8_URL=$(curl -s $URL | grep -oP '(?<=src=")[^"]*\.m3u8')
            echo "M3U8_URL=$M3U8_URL" >> $GITHUB_ENV
          done

      - name: Print M3U8 URLs
        run: |
          for URL in "${URLS[@]}"; do
            echo "The M3U8 URL for $URL is ${{ env.M3U8_URL }}"
          done
