name: M3U8 Finder with Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your preferred Node.js version

      - name: Install Playwright dependencies
        run: npm install playwright @playwright/test && npx playwright install chromium && npx playwright install firefox

      - name: Run script
        run: node playwright-script.js # Or whatever name you use for your script
        
      - name: Upload playlist
        uses: actions/upload-artifact@v4
        with:
            name: playlist
            path: playlist.m3u8
