name: Run m3u8_detector

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install puppeteer

    - name: Install yt-dlp
      run: sudo pip install yt-dlp

    - name: Run Puppeteer script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node puppeteer-script.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "qbasekostas@yahoo.com"
        git config --global user.name "qbasekostas"
        git add playlist.m3u8
        git commit -m "Update playlist.m3u8 with new entries"
        git pull --rebase || git rebase --abort
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
