name: M3U Playlist Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run M3U Detector
      run: npm start
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}

    - name: Commit and Push changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"
        git add .
        git commit -m "Add M3U playlist"
        git push -u origin main --force
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
