name: M3U8 Finder with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours


jobs:
  find_m3u8_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Playwright dependencies
      run: npm install playwright @playwright/test && npx playwright install chromium && npx playwright install firefox

    - name: Run M3U8 Finder Script
      run: node playwright-script.js

    - name: Commit and push playlist.m3u8
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add playlist.m3u8
        git commit -m "Update playlist.m3u8"
        git push
      
    - name: Upload playlist
      uses: actions/upload-artifact@v4
      with:
        name: playlist
        path: playlist.m3u8
