name: Run m3u8_detector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify installed packages
      run: |
        source venv/bin/activate
        pip freeze

    - name: Run m3u8_detector script
      run: |
        source venv/bin/activate
        python m3u8_detector.py

    - name: Commit and push playlist.m3u8
      run: |
        git config --global user.email "qbasekostas@yahoo.com"
        git config --global user.name "qbasekostas"
        cp /home/runner/work/SportTV/SportTV/playlist.m3u8 .
        git add playlist.m3u8
        git commit -m "Add playlist.m3u8"
        git push
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
