name: Run m3u8_detector

on:
  schedule:
    - cron: '0 13 * * *'  # 15:00 EET
    - cron: '0 15 * * *'  # 17:00 EET
    - cron: '0 17 * * *'  # 19:00 EET
    - cron: '0 19 * * *'  # 21:00 EET
    - cron: '0 21 * * *'  # 23:00 EET
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Upgrade pip
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installation
      run: |
        source venv/bin/activate
        pip show webdriver_manager
        python -c "from webdriver_manager.chrome import ChromeDriverManager; print('webdriver_manager imported successfully')"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run m3u8_detector script
        run: |
          source venv/bin/activate
          python m3u8_detector.py

      - name: Commit and push playlist.m3u8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "qbasekostas@yahoo.com"
          git config --global user.name "qbasekostas"
          git add playlist.m3u8
          git commit -m "Add playlist.m3u8"
          git pull --rebase  # Pull changes from remote
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
