name: Run m3u8_detector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify the Ubuntu version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/115.0.5790.102/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set ChromeDriver environment variable
      run: echo "CHROMEDRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

    - name: Verify installed packages
      run: |
        source venv/bin/activate
        pip freeze

    - name: Run m3u8_detector script
      run: |
        source venv/bin/activate
        python m3u8_detector.py
