name: Run m3u8_detector

on:
  schedule:
    - cron: '0 13 * * *'  # 15:00 EET
    - cron: '0 15 * * *'  # 17:00 EET
    - cron: '0 17 * * *'  # 19:00 EET
    - cron: '0 19 * * *'  # 21:00 EET
    - cron: '0 21 * * *'  # 23:00 EET
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Verify geckodriver installation
      run: |
        which geckodriver || echo "geckodriver not found"
        geckodriver --version || echo "Failed to run geckodriver"

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Upgrade pip
      run: |
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install dependencies from requirements.txt
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        source venv/bin/activate
        python m3u8_detector.py

    - name: Commit and push playlist.m3u8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "qbasekostas@yahoo.com"
        git config --global user.name "qbasekostas"
        git add playlist.m3u8
        git commit -m "Add playlist.m3u8"
        git pull --rebase
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
